export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          email: string | null;
          full_name: string | null;
          subscription_status: string;
          subscription_plan: string;
          stripe_customer_id: string | null;
          stripe_subscription_id: string | null;
          organization_id: string | null;
          institution_id: string | null;
          organization_access_type: string | null;
          organization_verified_at: string | null;
          role: string | null;
          app_role: string | null;
          account_type: string;
          resume_download_credits: number;
          optimization_credits: number;
          document_exports_used: number;
          optimization_credits_used: number;
          saved_versions_count: number;
          processed_stripe_event_ids: string[];
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          email?: string | null;
          full_name?: string | null;
          subscription_status?: string;
          subscription_plan?: string;
          stripe_customer_id?: string | null;
          stripe_subscription_id?: string | null;
          organization_id?: string | null;
          institution_id?: string | null;
          organization_access_type?: string | null;
          organization_verified_at?: string | null;
          role?: string | null;
          app_role?: string | null;
          account_type?: string;
          resume_download_credits?: number;
          optimization_credits?: number;
          document_exports_used?: number;
          optimization_credits_used?: number;
          saved_versions_count?: number;
          processed_stripe_event_ids?: string[];
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          email?: string | null;
          full_name?: string | null;
          subscription_status?: string;
          subscription_plan?: string;
          stripe_customer_id?: string | null;
          stripe_subscription_id?: string | null;
          organization_id?: string | null;
          institution_id?: string | null;
          organization_access_type?: string | null;
          organization_verified_at?: string | null;
          role?: string | null;
          app_role?: string | null;
          account_type?: string;
          resume_download_credits?: number;
          optimization_credits?: number;
          document_exports_used?: number;
          optimization_credits_used?: number;
          saved_versions_count?: number;
          processed_stripe_event_ids?: string[];
          created_at?: string;
          updated_at?: string;
        };
      };
      organizations: {
        Row: {
          id: string;
          name: string;
          type: string;
          email_domain: string;
          access_code: string;
          plan: string;
          seats_allowed: number;
          seats_used: number;
          status: string;
          start_date: string | null;
          end_date: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          type?: string;
          email_domain: string;
          access_code: string;
          plan?: string;
          seats_allowed?: number;
          seats_used?: number;
          status?: string;
          start_date?: string | null;
          end_date?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          type?: string;
          email_domain?: string;
          access_code?: string;
          plan?: string;
          seats_allowed?: number;
          seats_used?: number;
          status?: string;
          start_date?: string | null;
          end_date?: string | null;
          created_at?: string;
        };
      };
      institution_profiles: {
        Row: {
          id: string;
          user_id: string;
          institution_name: string;
          institution_type: string;
          admin_name: string;
          admin_email: string;
          website: string;
          country: string;
          state_region: string | null;
          city: string;
          student_email_domain: string;
          access_status: string;
          access_start_date: string | null;
          access_end_date: string | null;
          access_notes: string | null;
          estimated_student_coverage: number | null;
          seat_limit: number | null;
          active_seats: number;
          plan_type: string | null;
          auto_domain_access: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          institution_name?: string;
          institution_type?: string;
          admin_name?: string;
          admin_email?: string;
          website?: string;
          country?: string;
          state_region?: string | null;
          city?: string;
          student_email_domain?: string;
          access_status?: string;
          access_start_date?: string | null;
          access_end_date?: string | null;
          access_notes?: string | null;
          estimated_student_coverage?: number | null;
          seat_limit?: number | null;
          active_seats?: number;
          plan_type?: string | null;
          auto_domain_access?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          institution_name?: string;
          institution_type?: string;
          admin_name?: string;
          admin_email?: string;
          website?: string;
          country?: string;
          state_region?: string | null;
          city?: string;
          student_email_domain?: string;
          access_status?: string;
          access_start_date?: string | null;
          access_end_date?: string | null;
          access_notes?: string | null;
          estimated_student_coverage?: number | null;
          seat_limit?: number | null;
          active_seats?: number;
          plan_type?: string | null;
          auto_domain_access?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      recruiter_profiles: {
        Row: {
          id: string;
          user_id: string;
          company_name: string;
          recruiter_name: string;
          work_email: string;
          company_website: string | null;
          linkedin_company_url: string | null;
          phone_number: string;
          phone_verified: boolean;
          address_line_1: string;
          address_line_2: string | null;
          city: string;
          state_region: string;
          postal_code: string | null;
          country: string;
          company_location: string | null;
          industry: string | null;
          industry_other: string | null;
          company_size: string | null;
          hiring_focus: string | null;
          verification_status: string;
          verification_notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          company_name?: string;
          recruiter_name?: string;
          work_email?: string;
          company_website?: string | null;
          linkedin_company_url?: string | null;
          phone_number?: string;
          phone_verified?: boolean;
          address_line_1?: string;
          address_line_2?: string | null;
          city?: string;
          state_region?: string;
          postal_code?: string | null;
          country?: string;
          company_location?: string | null;
          industry?: string | null;
          industry_other?: string | null;
          company_size?: string | null;
          hiring_focus?: string | null;
          verification_status?: string;
          verification_notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          company_name?: string;
          recruiter_name?: string;
          work_email?: string;
          company_website?: string | null;
          linkedin_company_url?: string | null;
          phone_number?: string;
          phone_verified?: boolean;
          address_line_1?: string;
          address_line_2?: string | null;
          city?: string;
          state_region?: string;
          postal_code?: string | null;
          country?: string;
          company_location?: string | null;
          industry?: string | null;
          industry_other?: string | null;
          company_size?: string | null;
          hiring_focus?: string | null;
          verification_status?: string;
          verification_notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      job_posts: {
        Row: {
          id: string;
          recruiter_id: string;
          job_title: string;
          company_name: string;
          location: string;
          workplace_type: string;
          employment_type: string;
          salary_range: string | null;
          salary_currency: string | null;
          salary_min: number | null;
          salary_max: number | null;
          salary_period: string | null;
          role_summary: string;
          responsibilities: string;
          requirements: string;
          skills: string[];
          application_deadline: string | null;
          application_url: string | null;
          status: string;
          applicants_count: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          recruiter_id: string;
          job_title: string;
          company_name: string;
          location?: string;
          workplace_type?: string;
          employment_type?: string;
          salary_range?: string | null;
          salary_currency?: string | null;
          salary_min?: number | null;
          salary_max?: number | null;
          salary_period?: string | null;
          role_summary?: string;
          responsibilities?: string;
          requirements?: string;
          skills?: string[];
          application_deadline?: string | null;
          application_url?: string | null;
          status?: string;
          applicants_count?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          recruiter_id?: string;
          job_title?: string;
          company_name?: string;
          location?: string;
          workplace_type?: string;
          employment_type?: string;
          salary_range?: string | null;
          salary_currency?: string | null;
          salary_min?: number | null;
          salary_max?: number | null;
          salary_period?: string | null;
          role_summary?: string;
          responsibilities?: string;
          requirements?: string;
          skills?: string[];
          application_deadline?: string | null;
          application_url?: string | null;
          status?: string;
          applicants_count?: number;
          created_at?: string;
          updated_at?: string;
        };
      };
      job_applications: {
        Row: {
          id: string;
          job_id: string;
          candidate_id: string | null;
          candidate_user_id: string | null;
          candidate_email: string | null;
          recruiter_id: string;
          full_name: string;
          phone_number: string;
          location: string;
          short_note: string;
          resume_file_url: string | null;
          cover_letter_file_url: string | null;
          status: string;
          candidate_snapshot: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          job_id: string;
          candidate_id?: string | null;
          candidate_user_id?: string | null;
          candidate_email?: string | null;
          recruiter_id: string;
          full_name?: string;
          phone_number?: string;
          location?: string;
          short_note?: string;
          resume_file_url?: string | null;
          cover_letter_file_url?: string | null;
          status?: string;
          candidate_snapshot?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          job_id?: string;
          candidate_id?: string | null;
          candidate_user_id?: string | null;
          candidate_email?: string | null;
          recruiter_id?: string;
          full_name?: string;
          phone_number?: string;
          location?: string;
          short_note?: string;
          resume_file_url?: string | null;
          cover_letter_file_url?: string | null;
          status?: string;
          candidate_snapshot?: Json;
          created_at?: string;
          updated_at?: string;
        };
      };
      job_application_recruiter_notes: {
        Row: {
          application_id: string;
          recruiter_id: string;
          recruiter_note: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          application_id: string;
          recruiter_id: string;
          recruiter_note?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          application_id?: string;
          recruiter_id?: string;
          recruiter_note?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      job_alert_subscriptions: {
        Row: {
          id: string;
          candidate_id: string | null;
          email: string;
          keyword: string;
          keyword_query: string;
          title_preference: string;
          title_query: string;
          location_preference: string;
          location_query: string;
          job_type_preference: string;
          employment_type: string;
          workplace_type_preference: string;
          workplace_type: string;
          remote_only: boolean;
          status: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          candidate_id?: string | null;
          email: string;
          keyword?: string;
          keyword_query?: string;
          title_preference?: string;
          title_query?: string;
          location_preference?: string;
          location_query?: string;
          job_type_preference?: string;
          employment_type?: string;
          workplace_type_preference?: string;
          workplace_type?: string;
          remote_only?: boolean;
          status?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          candidate_id?: string | null;
          email?: string;
          keyword?: string;
          keyword_query?: string;
          title_preference?: string;
          title_query?: string;
          location_preference?: string;
          location_query?: string;
          job_type_preference?: string;
          employment_type?: string;
          workplace_type_preference?: string;
          workplace_type?: string;
          remote_only?: boolean;
          status?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      notifications: {
        Row: {
          id: string;
          user_id: string | null;
          email: string | null;
          type: string;
          title: string;
          message: string;
          related_job_id: string | null;
          related_application_id: string | null;
          read: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id?: string | null;
          email?: string | null;
          type: string;
          title: string;
          message: string;
          related_job_id?: string | null;
          related_application_id?: string | null;
          read?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string | null;
          email?: string | null;
          type?: string;
          title?: string;
          message?: string;
          related_job_id?: string | null;
          related_application_id?: string | null;
          read?: boolean;
          created_at?: string;
        };
      };
      resumes: {
        Row: {
          id: string;
          user_id: string;
          title: string;
          target_role: string | null;
          content_json: Json;
          template: string | null;
          theme: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          title: string;
          target_role?: string | null;
          content_json?: Json;
          template?: string | null;
          theme?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          title?: string;
          target_role?: string | null;
          content_json?: Json;
          template?: string | null;
          theme?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      resume_versions: {
        Row: {
          id: string;
          resume_id: string;
          version_name: string;
          content_json: Json;
          created_at: string;
        };
        Insert: {
          id?: string;
          resume_id: string;
          version_name: string;
          content_json?: Json;
          created_at?: string;
        };
        Update: {
          id?: string;
          resume_id?: string;
          version_name?: string;
          content_json?: Json;
          created_at?: string;
        };
      };
      exports: {
        Row: {
          id: string;
          user_id: string;
          resume_id: string | null;
          export_type: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          resume_id?: string | null;
          export_type: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          resume_id?: string | null;
          export_type?: string;
          created_at?: string;
        };
      };
      subscriptions: {
        Row: {
          id: string;
          user_id: string;
          stripe_customer_id: string | null;
          stripe_subscription_id: string | null;
          plan: string;
          status: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          stripe_customer_id?: string | null;
          stripe_subscription_id?: string | null;
          plan?: string;
          status?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          stripe_customer_id?: string | null;
          stripe_subscription_id?: string | null;
          plan?: string;
          status?: string;
          created_at?: string;
        };
      };
      ai_generations: {
        Row: {
          id: string;
          user_id: string;
          resume_id: string | null;
          prompt_type: string;
          tokens_used: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          resume_id?: string | null;
          prompt_type: string;
          tokens_used?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          resume_id?: string | null;
          prompt_type?: string;
          tokens_used?: number;
          created_at?: string;
        };
      };
    };
  };
};
