export const demoCandidate = {
  name: "Amara Johnson",
  roleGoal: "Product Analyst",
  location: "Irvine, CA",
  readinessScore: 76,
  careerAssets: [
    { label: "Resume profile", progress: 100, status: "Structured" },
    { label: "Cover letter framework", progress: 80, status: "Prepared" },
    { label: "LinkedIn positioning", progress: 65, status: "In progress" },
    { label: "Application kit", progress: 50, status: "Ready to refine" },
  ],
  applications: [
    { title: "Associate Product Manager", company: "Northshore Labs", status: "Submitted", date: "May 18, 2026" },
    { title: "AI Operations Analyst", company: "Atlas Digital", status: "Reviewing", date: "May 14, 2026" },
    { title: "Business Intelligence Intern", company: "CivicMetric", status: "Proceed", date: "May 10, 2026" },
    { title: "Marketing Coordinator", company: "Harbor Studio", status: "Rejected", date: "May 5, 2026" },
  ],
  notifications: [
    "Your application for AI Operations Analyst is now under review.",
    "Your application for Business Intelligence Intern has moved forward.",
  ],
};

export const demoRecruiter = {
  company: "Atlas Digital",
  recruiter: "Maya Chen",
  verificationStatus: "Verified Recruiter",
  jobs: [
    {
      title: "Associate Product Manager",
      applicants: 8,
      location: "Irvine, CA",
      workplaceType: "Hybrid",
      employmentType: "Full-time",
      summary: "Support product discovery, coordinate roadmap execution, and translate customer insight into measurable releases.",
      statusCounts: { Submitted: 3, Reviewing: 2, Proceed: 2, Rejected: 1 },
      previews: [
        {
          name: "Amara Johnson",
          status: "Submitted",
          materials: "Resume + cover letter",
          email: "amara.johnson@example.com",
          phone: "(949) 555-0148",
          location: "Irvine, CA",
          submittedDate: "May 22, 2026",
          headline: "Product Analyst transitioning into product management",
          note: "Strong product analysis foundation. Confirm prioritization examples and cross-functional delivery experience during review.",
        },
        {
          name: "Daniel Ortiz",
          status: "Reviewing",
          materials: "Resume",
          email: "daniel.ortiz@example.com",
          phone: "(714) 555-0182",
          location: "Costa Mesa, CA",
          submittedDate: "May 21, 2026",
          headline: "Associate product specialist with marketplace experience",
          note: "Resume shows solid experimentation exposure. Request clearer ownership of feature launch outcomes.",
        },
      ],
    },
    {
      title: "AI Operations Analyst",
      applicants: 5,
      location: "Remote, United States",
      workplaceType: "Remote",
      employmentType: "Full-time",
      summary: "Improve evaluation workflows and operational quality for data-driven product initiatives.",
      statusCounts: { Submitted: 2, Reviewing: 2, Proceed: 1 },
      previews: [
        {
          name: "Sophia Lee",
          status: "Proceed",
          materials: "Resume + cover letter",
          email: "sophia.lee@example.com",
          phone: "(415) 555-0127",
          location: "San Jose, CA",
          submittedDate: "May 20, 2026",
          headline: "Operations analyst focused on model evaluation quality",
          note: "Relevant quality-assurance workflow experience. Move forward with structured operations interview.",
        },
      ],
    },
    {
      title: "Customer Success Associate",
      applicants: 4,
      location: "Austin, TX",
      workplaceType: "Hybrid",
      employmentType: "Full-time",
      summary: "Manage customer onboarding, identify adoption blockers, and strengthen account outcomes.",
      statusCounts: { Submitted: 1, Reviewing: 1, Proceed: 1, Rejected: 1 },
      previews: [
        {
          name: "Jordan Brooks",
          status: "Reviewing",
          materials: "Resume",
          email: "jordan.brooks@example.com",
          phone: "(512) 555-0196",
          location: "Austin, TX",
          submittedDate: "May 18, 2026",
          headline: "Customer operations coordinator with SaaS onboarding experience",
          note: "Customer communication is clear. Assess renewal support exposure before proceeding.",
        },
      ],
    },
  ],
};

export const demoInstitution = {
  name: "Western Pacific University",
  package: "Department Access",
  seats: 1250,
  activeStudents: 842,
  status: "Active",
  seatsUsed: 67,
  applicationsSubmitted: 1426,
  recruiterEngagements: 318,
  materialsImproved: 1087,
  readinessScore: 74,
  applicationActivity: {
    Submitted: 620,
    Reviewing: 410,
    Proceed: 210,
    Rejected: 186,
  },
};
